spring.application.name=HUB

# # Configuração do PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/hubdb
# spring.datasource.username=postgres
# spring.datasource.password=sua_senha
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # Configuração do MongoDB
# spring.mongodb.uri=mongodb://localhost:27017/hubdb

# Configuração do Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
